# Main device IP for Wi-Fi mode
PHONE_IP=192.168.0.100

# Default ADB TCP port
ADB_PORT=5555

# Scrcpy video settings
MAX_SIZE=1024
MAX_FPS=60
VIDEO_BIT_RATE=16M

# Relative path to the scrcpy Windows release folder
SCRCPY_DIR=scrcpy-win64-v3.3.1
